const sidebars = {
  dates: [
    {
      type: 'category',
      label: 'Courtship Logs',
      items: [
        {
          type: 'autogenerated',
          dirName: 'dates',
        },
      ],
    },
  ],

  mainStory: ['main-story/index'],
  asmr: ['asmr/index'],
  cnExclusive: ['cn-exclusive/index'],
  misc: ['misc/index'],
};

export default sidebars;